//{{NO_DEPENDENCIES}}
// Arquivo de inclusão gerado pelo Microsoft Visual C++.
// Usado por PluginControls.rc
//
#define IDD_ABOUT                       102
#define IDB_HEREBEDRAGONS               103
#define IDD_HEREBEDRAGONS               104
#define IDD_PATHACCESSDIALOG            106
#define IDD_PARSERESULTS                108
#define IDD_COMPILERSETTINGS            117
#define IDD_BATCHPROCESS                120
#define IDD_PROCESSFILES                127
#define IDD_USERSPREFERENCES            130
#define IDD_LOGGER                      132
#define IDD_LOGGER_ERRORS               134
#define IDD_LOGGER_CONSOLE              136
#define IDB_NWSCRIPTLOGO                145
#define IDI_ABOUTBOX                    148
#define IDI_CLEARWINDOW                 149
#define IDI_COMPILEFILE                 150
#define IDI_COMPILEBATCH                151
#define IDI_DARKTHEME                   152
#define IDI_DEPENCENCYGROUP             153
#define IDI_DISASSEMBLECODE             154
#define IDI_IMMEDIATEWINDOW             155
#define IDI_IMPORTSETTINGS              156
#define IDI_REPEATLASTRUN               157
#define IDI_REPORT                      158
#define IDI_SETTINGSGROUP               159
#define IDI_SHOWASSIGNEDCONFIGURATION   160
#define IDI_UNDOCHECKBOXLIST            161
#define IDI_USERBUILD                   162
#define IDI_USERBUILDREMOVE             163
#define IDI_RESTART                     165
#define IDR_ABOUTDOC                    168
#define IDI_ERRORSQUIGGLE               169
#define IDI_WORDWRAP                    174
#define IDR_ABOUTDOCDARK                175
#define IDR_KNOWNOBJECTS                177
#define IDB_NWSCRIPTFILEPARSE           180
#define IDI_NEVERWINTERAPP              181
#define IDI_ANALISYS                    183
#define IDI_DESCRIPTIONVIEWER           184
#define IDI_FILEDESTINATION             185
#define IDI_GOTOLINE                    186
#define IDI_REPAIR                      187
#define IDB_NWSCRIPTLOGO_SIMPLIFIED     188
#define IDI_APPLICATIONACCESS           189
#define IDD_WHATISTHIS                  190
#define IDR_COMPILERENGINE              192
#define IDR_COMPILERENGINEDARK          193
#define IDR_SVG1                        194
#define IDI_HELPTABLECONTENTS           194
#define IDC_LNKHOMEPAGE                 1000
#define IDC_TXTABOUT                    1001
#define IDC_LBLPLUGINNAME               1002
#define IDC_LBLCOPYRIGHT                1003
#define IDC_LBLSPECIALCREDITS           1004
#define IDC_PCTLOGO                     1005
#define IDC_LBLHOMEPAGE                 1006
#define IDC_LBLVERSION                  1007
#define IDC_CHKOK                       1008
#define IDC_TXTREQUIREDFILES            1009
#define IDC_SHIELDICON                  1010
#define IDC_LBLWARNING                  1011
#define IDC_PCTNWSCRIPTFILE             1012
#define IDC_LBLENGINESTRUCTS            1013
#define IDC_LBLFUNCTIONDEFINITIONS      1014
#define IDC_LBLGLOBALCONSTANTS          1015
#define IDC_LBLFILESUMARY               1016
#define IDC_LBLKEEPRESULTS              1017
#define IDC_USENWN1                     1018
#define IDC_TXTNWN1INSTALL              1019
#define IDC_BTNWN1INSTALL               1020
#define IDC_USENWN2                     1021
#define IDC_TXTNWN2INSTALL              1022
#define IDC_BTNWN2INSTALL               1023
#define IDC_CHKIGNOREINSTALLPATHS       1024
#define IDC_TXTADDPATH                  1025
#define IDC_BTSEARCHPATH                1026
#define IDC_LSTADDPATH                  1027
#define IDC_BTADDPATH                   1028
#define IDC_BTDELPATH                   1029
#define IDC_CHKCOMPOPTIMIZE             1030
#define IDC_CHKCOMPSTRICTMODE           1031
#define IDC_CHKCOMPNDBSYMBOLS           1032
#define IDC_CHKCOMPMAKEFILE             1033
#define IDC_CHKCOMPDISABLESLASHPARSE    1034
#define IDC_CBOTARGETVERSION            1035
#define IDC_CHKOUTPUTDIR                1036
#define IDC_TXTOUTPUTDIR                1037
#define IDSTART                         1038
#define IDC_BTOUTPUTDIR                 1039
#define IDC_TXTBATCHDIRSTART            1040
#define IDC_TXTOUTPUTDIRBATCH           1041
#define IDC_CHKRECURSIVE                1042
#define IDC_BTOUTPUTDIRBATCH            1043
#define IDC_TXTBATCHFILTERS             1045
#define IDC_RDCOMPILE                   1047
#define IDC_RDDISASM                    1049
#define IDC_CHKCONTINUEONFAIL           1050
#define IDC_BTBATCHDIRSTART             1051
#define IDC_LBLSTATUS                   1052
#define IDC_CHKOUTPUTDIRBATCH           1053
#define IDC_CHKNONBIOWAREXTENSIONS      1054
#define IDC_CHKAUTOOPENDISASSEMBLED     1055
#define IDC_CHKAUTOOPENDEBUGSYMBOLS     1056
#define IDC_CHKAUTOINSTALLDARKTHEME     1057
#define IDC_TABLOGGER                   1060
#define IDC_TXTCONSOLE                  1062
#define IDC_LSTERRORS                   1067
#define IDC_ERRORGROUPBOX               1068
#define IDC_LBLCONSOLE                  1069
#define IDC_BTCLEARCONSOLE              1072
#define IDC_BTTOGGLEWORDWRAP            1073
#define IDC_BTFILTERERRORS              1074
#define IDC_BTFILTERWARNINGS            1075
#define IDC_BTFILTERINFO                1077
#define IDC_LBLDARKMODEEXPLAIN          1077
#define IDC_PCTNWSCRIPTFILELOGOBOX      1079
#define IDC_PCTABOUTLOGOBOX             1080
#define IDC_PCTFILEACCESSLOGOBOX        1081
#define IDC_USEBEAMDOGCOMPILER          1082
#define IDC_USELEGACYCOMPILER           1083
#define IDC_WHATISTHIS                  1084
#define IDC_LNKWHATISTHIS               1084
#define IDC_LBLTARGETVERSION            1085
#define IDC_TXTHELP                     1086
#define IDC_STATIC                      -1
#define IDC_HEREBEDRAGONS               -1
#define IDC_LBLSOLUTION                 -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
