/** @file NWScriptCompiler.cpp
 * Invokes various functions from NscLib compiler/interpreter library.
 *
 **/
 // Copyright (C) 2022 - Leonardo Silva 
 // The License.txt file describes the conditions under which this software may be distributed.


#include "pch.h"
//#include <fstream>
//#include "jpcre2.h"

#include "NWScriptCompiler.h"
#include "VersionFromResource.h"

using namespace NWScriptPlugin;
typedef NWScriptLogger::LogType LogType;

#define DEPENDENCYHEADER " \
/*************************************************************************************** \r\n\
 * Dependency files descriptor for \"%DEPENDENCYFILE%\"\r\n\
 * Generated by NWScript Tools for Notepad++ (%VERSION%)\r\n\
 *\r\n\
 * Generation date: %GENERATIONDATE%\r\n\
 ***************************************************************************************/\r\n\
\r\n\
"

#define SCRIPTERRORPREFIX "Error"
#define FORMATDISASMREGEX R"(.+)"
#define DEPENDENCYPARSEREGEX R"(([^\/]+)\/([^\\\n]+))"

typedef jpcre2::select<char> pcre2;
static pcre2::Regex assemblyLine(FORMATDISASMREGEX, PCRE2_MULTILINE, jpcre2::JIT_COMPILE);
static pcre2::Regex dependencyParse(DEPENDENCYPARSEREGEX, 0, jpcre2::JIT_COMPILE);

bool NWScriptCompiler::initialize() {

    // Critical path, initialize resources
    try
    {
        _resourceManager = std::make_unique<ResourceManager>(&_logger);
    }
    catch (std::runtime_error& e)
    {
        _logger.log("Failed to initialize the resources manager:", LogType::Critical, "NSC2001", true);
        _logger.log(e.what(), LogType::Critical, true);
        return false;
    }

    NWNHome = getNwnHomePath(_settings->compileVersion);

    return true;
}

bool NWScriptCompiler::LoadScriptResources()
{
    ResourceManager::ModuleLoadParams LoadParams;
    ResourceManager::StringVec KeyFiles;

    ZeroMemory(&LoadParams, sizeof(LoadParams));

    LoadParams.SearchOrder =  ResourceManager::ModSearch_PrefDirectory;
    LoadParams.ResManFlags =  ResourceManager::ResManFlagNoGranny2;
    LoadParams.ResManFlags |= ResourceManager::ResManFlagErf16;

    if (_settings->compileVersion == 174) 
    {
#ifdef _WINDOWS
        KeyFiles.push_back("data\\nwn_base");
#else
        KeyFiles.emplace_back("data/nwn_base");
#endif // _WINDOWS
    }
    else 
    {
        KeyFiles.emplace_back("xp3");
        KeyFiles.emplace_back("xp2patch");
        KeyFiles.emplace_back("xp2");
        KeyFiles.emplace_back("xp1");
        KeyFiles.emplace_back("chitin");
    }

    LoadParams.KeyFiles = &KeyFiles;
    LoadParams.ResManFlags |= ResourceManager::ResManFlagBaseResourcesOnly;

    // Legacy code is using ASCII string names. We convert here. Also, many exceptions thrown inside those classes to deal with.
    std::string InstallDir = _settings->getChosenInstallDir() + "\\";
    try {
        _resourceManager->LoadScriptResources(wstr2str(NWNHome), InstallDir, &LoadParams);
    }
    catch(...) { 
        //_resourceManager is writting to the log messages here, so we just return false.
        return false;
    }

    return true;
}

bool NWScriptCompiler::processFile(filesystem::path& sourcePath, filesystem::path& destDir, bool fromMemory, char* fileContents)
{
    _logger.log("Initializing process...", LogType::ConsoleMessage);

    NWN::ResType fileResType;
    NWN::ResRef32 fileResRef;
    std::string inFileContents;

    // First check... is the compiler initialized?
    if (!isInitialized())
    {
        if (!initialize())
            return false;

        // Start building up search paths. 
        _includePaths.push_back(wstr2str(sourcePath.parent_path()));

        if (!_settings->ignoreInstallPaths)
        {
            if (!LoadScriptResources())
            {
                _logger.log("Could not load script resources on installation path: " + _settings->getChosenInstallDir(), LogType::Warning);
            }

            if (_settings->compileVersion == 174)
            {
                std::string overrideDir = _settings->getChosenInstallDir() + "\\ovr\\";
                _includePaths.push_back(overrideDir);
            }
        }

        for (generic_string s : _settings->getIncludeDirsV())
        {
            _includePaths.push_back(properDirNameA(wstr2str(s)) + "\\");
        }

        if (_settings->compileMode == 0)
            _logger.log("Compiling script:" + wstr2str(sourcePath), LogType::Info);
        else
            _logger.log("Disassembling binary:" + wstr2str(sourcePath), LogType::Info);

        // Acquire information about NWN Resource Type of the file. Warning of ignored result is incorrect.
#pragma warning (push)
#pragma warning (disable : 6031)
        fileResType = _resourceManager->ExtToResType(wstr2str(sourcePath).c_str());
        fileResRef = _resourceManager->ResRef32FromStr(wstr2str(sourcePath.stem()).c_str());
#pragma warning (pop)

        inFileContents;
        if (fromMemory)
            inFileContents = fileContents;
        else
        {
            if (!fileToBuffer(sourcePath.c_str(), inFileContents))
            {
                _logger.log("Could not load the specified file: " + wstr2str(sourcePath), LogType::Error, "NSC2002");
                return false;
            }
        }

        // Create our compiler/disassembler
        _compiler = std::make_unique<NscCompiler>(*_resourceManager, _settings->useNonBiowareExtenstions);
        _compiler->NscSetIncludePaths(_includePaths);
        _compiler->NscSetCompilerErrorPrefix(SCRIPTERRORPREFIX);
        _compiler->NscSetResourceCacheEnabled(true);
    }

    // Execute the process
    if (_settings->compileMode == 0)
    {
        _logger.log("Compiling script: " + sourcePath.string(), LogType::ConsoleMessage);
        return compileScript(sourcePath, destDir, fromMemory, inFileContents, fileResType, fileResRef);
    }
    else
    {
        _logger.log("Disassembling binary: " + sourcePath.string(), LogType::ConsoleMessage);
        return disassembleBinary(sourcePath, destDir, fromMemory, inFileContents, fileResType, fileResRef);
    }
}


bool NWScriptCompiler::compileScript(filesystem::path& sourcePath, filesystem::path& destDir, bool fromMemory, std::string& fileContents,
    const NWN::ResType& fileResType, const NWN::ResRef32& fileResRef)
{
    // We always ignore include files. And for our project, the compiler ALWAYS
    // return include dependencies, since message filters are done in a higher application layer.
    bool bIgnoreIncludes = true;
    _settings->compilerFlags |= NscCompilerFlag_ShowIncludes;

    // Main compilation step
    std::string dataRef;                     // Buffer to file is generic and requires a std::string
    swutil::ByteVec generatedCode;
    swutil::ByteVec debugSymbols;
    std::set<std::string> fileDependencies;

    NscResult result = _compiler->NscCompileScript(fileResRef, fileContents.c_str(), fileContents.size(), _settings->compileVersion,
        _settings->optimizeScript, bIgnoreIncludes, &_logger, _settings->compilerFlags, generatedCode, debugSymbols, fileDependencies);

    switch (result)
    {
    case NscResult_Failure:
    {
        _logger.log("Compilation aborted with errors.", LogType::ConsoleMessage);
        return false;
    }

    case NscResult_Include:
    {
        _logger.log(sourcePath.filename().string() + " is an include file, ignored.", LogType::ConsoleMessage);
        return true;
    }

    case NscResult_Success:
        break;

    default:
        _logger.log("Unknown status code", LogType::ConsoleMessage);
        return false;
    }

    // Now save code data
    generic_string outputPath = str2wstr(destDir.string() + "\\" + sourcePath.stem().string() + ".ncs");
    dataRef.assign(reinterpret_cast<char*>(&generatedCode[0]), generatedCode.size());
    if (!bufferToFile(outputPath, dataRef))
    {
        _logger.log(TEXT("Error: could not write compiled output file: ") + outputPath, LogType::ConsoleMessage);
        return false;
    }

    // Save debug symbols if apply
    if (_settings->generateSymbols)
    {
        dataRef.clear();
        outputPath = str2wstr(destDir.string() + "\\" + sourcePath.stem().string() + ".ndb");
        dataRef.assign(reinterpret_cast<char*>(&debugSymbols[0]), debugSymbols.size());
        if (!bufferToFile(outputPath, dataRef))
        {
            _logger.log(TEXT("Error: could not write generated symbols output file: ") + outputPath, LogType::ConsoleMessage);
            return false;
        }
    }

    // And file dependencies if apply
    if (_settings->compilerFlags & NscCompilerFlag_GenerateMakeDeps)
        return WriteDependencies(sourcePath, destDir, fileDependencies);

    return true;
}


bool NWScriptCompiler::disassembleBinary(filesystem::path& sourcePath, filesystem::path& destDir, bool fromMemory, std::string& fileContents,
    const NWN::ResType& fileResType, const NWN::ResRef32& fileResRef)
{
    std::string generatedCode;

    // Main disassemble step.
    _compiler->NscDisassembleScript(fileContents.c_str(), fileContents.size(), generatedCode);

    // This is the way the library returns errors to us on that routine... :D
    if (generatedCode == "DISASSEMBLY ERROR: COMPILER INITIALIZATION FAILED!")
    {
        _logger.log("Error disassembling file. Compiler Initialization failed!", LogType::Error);
        return false;
    }

    // Save file, but first, we remove extra carriage returns the library is generating...
    generic_string outputPath = str2wstr(destDir.string() + "\\" + sourcePath.stem().string() + ".ncs.pcode");
    
    std::stringstream formatedCode;
    pcre2::VecNum matches;
    pcre2::RegexMatch fileMatcher(&assemblyLine);
    size_t lineCount = fileMatcher.setSubject(generatedCode).setModifier("gm").setNumberedSubstringVector(&matches).match();

    for (size_t i = 0; i < lineCount; i++)
        formatedCode << matches[i][0];

    if (!bufferToFile(outputPath, formatedCode.str()))
    {
        _logger.log(TEXT("Error: could not write disassembled output file: ") + outputPath, LogType::ConsoleMessage);
        return false;
    }

    return true;
}


bool NWScriptCompiler::WriteDependencies(const filesystem::path& sourcePath, const filesystem::path& destDir, const std::set<std::string>& dependencies)
{
    // Generate some timestamp headers
    char timestamp[128]; time_t currTime;  struct tm currTimeP;
    time(&currTime);
    errno_t error = localtime_s(&currTimeP, &currTime);
    strftime(timestamp, 64, "%B %d, %Y - %R", &currTimeP);

    // Get version from module's binary file
    DllVersion versionInfo = GetVersionFromResource();
    std::stringstream sVersion = {};
    sVersion << "version " << versionInfo.wLeftMost << "." << versionInfo.wSecondLeft << "." <<
        versionInfo.wSecondRight << " - build " << versionInfo.wRightMost;

    std::map<std::string, std::string> variablesMap;

    variablesMap.insert({ "%DEPENDENCYFILE%", sourcePath.filename().string() });
    variablesMap.insert({ "%VERSION%", sVersion.str() });
    variablesMap.insert({ "%GENERATIONDATE%", timestamp });

    // Input header information
    std::stringstream sdependencies;
    sdependencies << replaceStringsA(DEPENDENCYHEADER, variablesMap);

    // Main dependencies
    sdependencies << "  1) Main file relation (compiled script -> script)" << "\r\n\r\n";
    sdependencies << "     Source Directory: " + sourcePath.parent_path().string() << "\r\n";
    sdependencies << "     Destination Directory: " + destDir.string() << "\r\n";
    sdependencies << "          " + sourcePath.stem().string() << ".ncs <- generated from -> " << sourcePath.stem().string() << ".nss" << "\r\n\r\n";

    // Additional dependencies
    if (!dependencies.empty())
    {
        sdependencies << "  2) Dependencies of script source: " << sourcePath.stem().string() << ".nss" << "\r\n\r\n";

        pcre2::VecNum matches;
        pcre2::RegexMatch dependencyParser(&dependencyParse);
        dependencyParser.setNumberedSubstringVector(&matches);

        // Get first path in dependencies for comparisons.
        auto it = dependencies.begin();
        int count = dependencyParser.setSubject(*it).match();
        filesystem::path currentPath = matches[0][1];
        filesystem::path comparePath;

        // For each different path, we write the topic information of that folder and then enumerate the files
        int topicNumber = 1;
        bool bTopicWritten = false;
        for (auto& dependency : dependencies)
        {
            count = dependencyParser.setSubject(dependency).match();
            comparePath = matches[0][1];     // first capture group = directory name.
            if (currentPath != comparePath)
            {
                sdependencies << "\r\n";
                currentPath = comparePath;
                bTopicWritten = false;
                topicNumber++;
            }

            if (!bTopicWritten)
            {
                sdependencies << "        2." << topicNumber << ") Dependencies from: " << currentPath.string() << "\r\n\r\n";
                bTopicWritten = true;
            }

            sdependencies << "                   -> " << matches[0][2] << "\r\n"; // Second capture group = filename
        }

        sdependencies << "\r\n\r\n";
        sdependencies << "------------------[ END OF FILE DEPENDENCIES ]------------------" << "\r\n\r\n";

        generic_string outputPath = str2wstr(destDir.string() + "\\" + sourcePath.stem().string() + ".nss.dependencies");
        if (!bufferToFile(outputPath, sdependencies.str()))
        {
            _logger.log(TEXT("Error: could not write dependency file: ") + outputPath, LogType::ConsoleMessage);
            return false;
        }
    }

    return true;

}