/** @file xmlgenstring.h
 * Define some XML headers and comments for file generation.
 *
 * 
 * Copyright (C) 2022 - Leonardo Silva 
 * The License.txt file describes the conditions under which this software may be distributed.
 **/
 
#pragma once

// Some comments for the XML auto-generation features

#define XMLMANIFEST R"(<?xml version="1.0" encoding="UTF-8"?>
)"

#define XMLDOCHEADER R"(
This XML document was generated by 'NWScript Tools Plugin for Notepad++', please avoid manually editing it.

Plugin Homepage: https://github.com/Leonard-The-Wise/NWScript-Npp

Copyright (C) 2022 - Leonardo Silva
The License.txt file on the plugin homepage describes the conditions under which this software may be distributed.

)"

#define XMLAUTOCLANGCOMMENT R"(  The language Attribute here doesn't really do anything, it's more of a comment.  )"

#define XMLAUTOCENVCOMMENT R"(
		Environment specifies how the language should be interpreted. ignoreCase makes autocomplete
		ignore any casing, start and stopFunc specify what chars a function starts and stops with.
		param specifies parameter separator and terminal can be used to specify a character that stops
		any function. Using the same character for different functions results in undefined behaviour.
		
		The basic word character are : A-Z a-z 0-9 and '_' 
		If your function name contains other characters,
		add your characters in "additionalWordChar" attribute (without separator)
		in order to make calltip hint work.  )"

#define XMLAUTOCSORTNOTICE R"(
		The following items should be alphabetically ordered.
		func="yes" means the keyword should be treated as a fuction, and thus can be used in the parameter
		calltip system. If this is the case, the retVal attribute specifies the return value/type. Any
		following Param tag specifies a parameter, they must be in order. The name attributes specifies
		the parameter name.  )"

#define XMLPLUGINLANGUAGECOMMENT R"(
		The Language subsection defines which languages are supported by a Plugin. The name attribute is the
		name of the language (instead of the name of the plugin), ext is the associated file extension(s)
		for that language, commentLine defines which tokens mark a single comment, commentStart and commentEnd 
		are used to define which tokens mark the start and the end of multilined comments respectively. )"

#define XMLPLUGINKEYWORDCOMMENT R"(
			The Keywords tags defines which keywords are supported by the language lexer and should be colorized. 
			Notepad++ supports up to 8 keyword classes (or elements) definitions. Here we're setting all 8 classes 
			to use with NWScript language - defined under the <Keywords name=""> attribute. These tags aren't mean
			to be edited manually, use the Plugin import functions for user-defined types instead.
				1) instre1 -> reserved for storing all basic language Instruction Set;
				2) type1   -> reserved for storing all basic script variable names;
				3) type2   -> reserved for storing all engine structures defined in nwscript.nss file;
				4) type3   -> reserved for storing the exclusive markup of the "object" class and derivates (OBJECT_SELF and OBJECT_INVALID);
				5) type4   -> reserved for storing all constant names defined in nwscript.nss file;
				6) type5   -> open for user-defined constants (edit it in Settings -> Style Configurator, or import via the Tools);
				7) type6   -> reserved for storing all engine functions defined in nwscript.nss file;
				8) type7   -> open for user-defined function definitions (edit it in Settings -> Style Configurator, or import via the Tools);  )"

#define XMLPLUGINLEXERTYPECOMMENT R"(
		The LexerType section links a set of color styles to the above Language. So both name attribute of Language and LexerType 
		must match. The desc here is what Notepad++ shows for the user when he is editing language colors on the Settings panel. 
		Ext is currently unused by Notepad++ and most languages just set it to empty.  )"

#define XMLPLUGINWORDSTYLECOMMENT R"(
			The WordStyle tags describe how to colorize each type of language token. Here, all WordStyles which have a 
			<WordStyle keywordClass=""> attribute must match with a respective language <Keyword name="">. All other unassociated 
			tags are treated internally by the language lexer, such as Preprocessor Directives, Default colors, Numbers, Strings, 
			Operators and Comments.
			The name is what Notepad++ displays to the user in the Settings -> Style Configurator box.
			The styleID attribute is an internal number the lexer software uses to associate classes and should NEVER be changed.  )"

#define XMLDARKMODEDEFAULT R"(
<?xml version="1.0" encoding="UTF-8"?>
<NotepadPlus>
    <LexerStyles>
        <LexerType name="NWScript" desc="NWScript files" ext="">
            <WordsStyle name="PREPROCESSOR" styleID="9" fgColor="FFCFAF" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="DEFAULT" styleID="11" fgColor="DCDCCC" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="INSTRUCTION WORD" styleID="5" fgColor="DFC47D" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" keywordClass="instre1" />
            <WordsStyle name="TYPE WORD" styleID="16" fgColor="CEDF99" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" keywordClass="type1" />
            <WordsStyle name="ENGINE TYPE" styleID="28" fgColor="FF80FF" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" keywordClass="type2" />
            <WordsStyle name="OBJECT TYPE" styleID="29" fgColor="CEDF99" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" keywordClass="type3" />
            <WordsStyle name="ENGINE CONSTANT" styleID="30" fgColor="8F9E81" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" keywordClass="type4" />
            <WordsStyle name="CUSTOM CONSTANT" styleID="31" fgColor="B1B163" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" keywordClass="type5"/>
            <WordsStyle name="ENGINE FUNCTION" styleID="32" fgColor="BE7DFF" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" keywordClass="type6" />
            <WordsStyle name="USER FUNCTION" styleID="36" fgColor="E28CFF" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" keywordClass="type7"/>
            <WordsStyle name="NUMBER" styleID="4" fgColor="8CCFD2" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING" styleID="6" fgColor="CC9393" bgColor="3F3F3F" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="OPERATOR" styleID="10" fgColor="9F9D6C" bgColor="3F3F3F" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="COMMENT" styleID="1" fgColor="809F9F" bgColor="3F3F3F" fontName="" fontStyle="3" fontSize="" />
            <WordsStyle name="COMMENT LINE" styleID="2" fgColor="809F80" bgColor="3F3F3F" fontName="" fontStyle="3" fontSize="" />
        </LexerType>
    </LexerStyles>
</NotepadPlus>
)"

#define XMLDEFAULTSTYLER R"(
<?xml version="1.0" encoding="UTF-8"?>  
<NotepadPlus>
	<LexerStyles>
        <LexerType name="NWScript" desc="NWScript files" ext="">
            <WordsStyle name="PREPROCESSOR" styleID="9" fgColor="804000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="DEFAULT" styleID="11" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="INSTRUCTION WORD" styleID="5" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre1" />
            <WordsStyle name="TYPE WORD" styleID="16" fgColor="AA00AA" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type1" />
            <WordsStyle name="ENGINE TYPE" styleID="28" fgColor="FF09FF" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type2" />
            <WordsStyle name="OBJECT TYPE" styleID="29" fgColor="0065CA" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="type3" />
            <WordsStyle name="ENGINE CONSTANT" styleID="30" fgColor="0075EA" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type4" />
            <WordsStyle name="CUSTOM CONSTANT" styleID="31" fgColor="0057AE" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type5" />
            <WordsStyle name="ENGINE FUNCTION" styleID="32" fgColor="8000FF" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type6" />
            <WordsStyle name="USER FUNCTION" styleID="36" fgColor="5200A4" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type7" />
            <WordsStyle name="NUMBER" styleID="4" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="STRING" styleID="6" fgColor="808080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="OPERATOR" styleID="10" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" />
            <WordsStyle name="COMMENT" styleID="1" fgColor="008080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
            <WordsStyle name="COMMENT LINE" styleID="2" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" />
        </LexerType>
	</LexerStyles>
</NotepadPlus>
)"


#define ABOUT_TITLE TEXT("ABOUT THIS PLUGIN\r\n\
=====================================\r\n")

#define ABOUT_TEXT TEXT( \
"\r\n\
** For a more detailed and formated version of the help text, please visit the web page on the \"Online Help\" menu. **\r\n\
\r\n\
** Diagnostics information and some use statistics are avaliable at the end of this text. **\r\n\
\r\n\
USAGE:\r\n\
--------------------------\r\n\
• Editor Syntax Highlighting:\r\n\
   - Select NWScript Language from Languages menu to enable syntax highlighting.\r\n\
\r\n\
• Using Auto-Indentation:\r\n\
   - For Notepad++ 8.3.2 and bellow, chose the option \"Use Auto-Indentation\" to enable the plugin's built-in auto-indentation support. \
You'll need to disable Notepad++ Auto-Indentation in user preferences to avoid any conflicts. This feature is automatic on Notepad++ 8.3.3 \
and beyond so this menu option won't show anymore for users with up-to-date versions.\r\n\
\r\n\
• Menu - \"Compile script\":\r\n\
   - Compiles the current opened document into the \"Output Directory\" set in \"Compiler Settings\".\r\n\
\r\n\
• Menu - \"Disassemble file\":\r\n\
   - Disassembles a compiled NWscript file from the disk and put results into the \"Output Directory\" set in \"Compiler Settings\".\r\n\
\r\n\
• Menu - \"Batch processing\":\r\n\
   - Opens the Batch-processing dialog box.\r\n\
\r\n\
• Menu - \"Run last batch\":\r\n\
   - Runs the last successful batch operation in this session.\r\n\
\r\n\
• Menu - \"Fetch preprocessor output\":\r\n\
   - Runs a compile preprocessing phase on current script and display the results in a new document for the user. \
Useful to view what final text the compiler will ACTUALLY use to compile the script.\r\n\
\r\n\
• Menu - \"View Script Dependencies\":\r\n\
   - Parse the script file's dependencies and display to the user as a new human-readable document.\r\n\
\r\n\
• Menu - \"Compiler settings\":\r\n\
   - Opens the compiler settings.\r\n\
\r\n\
• Menu - \"User's Preferences\":\r\n\
   - Opens the user's preferences dialog.\r\n\
\r\n\
• Menu - \"Install Dark Theme\":\r\n\
   - Installs Dark Theme support if not already present. (When installation is detected, this option won't show up).\r\n\
\r\n\
• Menu - \"Import NWScript definitions\":\r\n\
   - With this option, you may import a new \"nwscript.nss\" to replace the current engine definitions like constants, functions and engine \
structures to use with syntax coloring and highlighting and also this enables the Auto Complete functions to them. This will overwrite any \
previous engine definitions present on the plugin configuration.\r\n\
\r\n\
• Menu - \"Import user-defined tokens\":\r\n\
   - With this option, you may import new user-defined functions and constants from any .nss file to enable color-syntax highlighting and auto-completion to them. \
Please notice that only function DECLARATIONS and GLOBAL CONSTANTS will be imported in this process. \
And if you have any user-defined functions and constants previously imported or in use, don't worry, they will be preserved, as long as you did NOT \
put them manually inside the reserved sections of the XML configuration file. So I advise you to NEVER edit that file manually. Like, ever!\r\n\
\r\n\
• Menu - \"Reset user-defined tokens\":\r\n\
   - This will clear ANY user-defined functions and constants previously imported to the plugin's configurations.\r\n\
\r\n\
• Menu - \"Reset editor colors\":\r\n\
   - This will reset all editor color styles to the default values - eihter for light and dark themes. No function or constants definitions will be ereased in the process.\r\n\
\r\n\
• Menu - \"About me\":\r\n\
   - Self reference ®. :)\r\n\
\r\n\
\r\n\
REMARKS:\r\n\
--------------------------\r\n\
• If you noticed the SHIELD icons near some menu options, that's because if you want to use that option you must either run Notepad++ with\
administrator privileges OR you may also manually provide write permissions to the option's required files (you'll be notified of which file you\
need to provide permissions to for each option.\r\n\
\r\n\
\r\n\
EXTRA COPYRIGHT INFO:\r\n\
--------------------------\r\n\
\r\n\
Copyright notices for embbeded version of the NWScript Compiler Library:\r\n\
\r\n\
  Portions Copyright (C) 2008-2015 Skywing\r\n\
  Portions copyright (C) 2002-2003, Edward T. Smith\r\n\
  Portions copyright (C) 2003, The Open Knights Consortium\r\n\
  Adapted for Neverwinter Nights Enhanced Edition and cross platform use by: Glorwinger and Jakkn\r\n\
  Readapted for Windows GUI applications by: Leonard-The-Wise\r\n\
\r\n\
\r\n\
SELF-DIAGNOSTICS:\r\n\
--------------------------\r\n\
  - Auto-Indentation: %NWSCRIPTINDENT%\r\n\
  - Dark Mode Theme:  %DARKTHEMESUPPORT%\r\n\
\r\n\
\r\n\
NERDY STATISTICS:\r\n\
--------------------------\r\n\
  - Number of compilations attempts: %COMPILEATTEMPTS%\r\n\
  - Successful compilations:         %COMPILESUCCESSES%\r\n\
  - Failed compilations:             %COMPILESFAILED%\r\n\
\r\n\
  - NWscript defined structures:     %engineStructures%\r\n\
  - NWScript defined functions:      %engineFunctionCount%\r\n\
  - NWScript defined constants:      %engineConstants%\r\n\
  - User defined structures:         %userStructures%\r\n\
  - User defined functions:          %userFunctionCount%\r\n\
  - User defined constants:          %userConstants%\r\n\
\r\n\
")


#define XMLFUNCTIONLIST "\
<NotepadPlus>\r\n\
	<functionList>\r\n\
		<!-- ================================================ [ NWScript ] -->\r\n\
\r\n\
		<parser\r\n\
			displayName=\"NWScript\"\r\n\
			id         =\"nwscript_function\"\r\n\
			commentExpr=\"(?s:/\\*.*?\\*/)|(?m-s://.*?$)\"\r\n\
		>\r\n\
			<function\r\n\
				mainExpr=\"^\\s*((?:\\w{3,}\\s+\\w+){1}\\s*\\((?:[^\\)\\(\\\"]|\"(?:\\\\.|[^\"\\\\]*+)*+\")*\\))(?:\\s*\\{)\"\r\n\
			>\r\n\
				<functionName>\r\n\
					<nameExpr expr=\"^\\w+\\s*(\\w+)\" />\r\n\
				</functionName>\r\n\
			</function>\r\n\
		</parser>\r\n\
	</functionList>\r\n\
</NotepadPlus>\r\n\
"

#define XMLPLUGINLEXERCONFIG R"(<NotepadPlus>
    <Languages>
        <!--
		The Language subsection defines which languages are supported by a Plugin. The name attribute is the
		name of the language (instead of the name of the plugin), ext is the associated file extension(s)
		for that language, commentLine defines which tokens mark a single comment, commentStart and commentEnd 
		are used to define which tokens mark the start and the end of multilined comments respectively. -->
        <Language name="NWScript" ext="nss" commentLine="//" commentStart="/*" commentEnd="*/">
            <!--
			The Keywords tags defines which keywords are supported by the language lexer and should be colorized. 
			Notepad++ supports up to 8 keyword classes (or elements) definitions. Here we're setting all 8 classes 
			to use with NWScript language - defined under the <Keywords name=""> attribute. These tags aren't mean
			to be edited manually, use the Plugin import functions for user-defined types instead.
				1) instre1 -> reserved for storing all basic language Instruction Set;
				2) type1   -> reserved for storing all basic script variable names;
				3) type2   -> reserved for storing all engine structures defined in nwscript.nss file;
				4) type3   -> reserved for storing the exclusive markup of the "object" class and derivates (OBJECT_SELF and OBJECT_INVALID);
				5) type4   -> reserved for storing all constant names defined in nwscript.nss file;
				6) type5   -> open for user-defined constants (edit it in Settings -> Style Configurator, or import via the Tools);
				7) type6   -> reserved for storing all engine functions defined in nwscript.nss file;
				8) type7   -> open for user-defined function definitions (edit it in Settings -> Style Configurator, or import via the Tools);  -->
            <Keywords name="instre1"></Keywords>
            <Keywords name="type1"></Keywords>
            <Keywords name="type2"></Keywords>
            <Keywords name="type3"></Keywords>
            <Keywords name="type4"></Keywords>
            <Keywords name="type5"/>
            <Keywords name="type6"></Keywords>
            <Keywords name="type7"/>
        </Language>
    </Languages>
    <LexerStyles>
        <!--
		The LexerType section links a set of color styles to the above Language. So both name attribute of Language and LexerType 
		must match. The desc here is what Notepad++ shows for the user when he is editing language colors on the Settings panel. 
		Ext is currently unused by Notepad++ and most languages just set it to empty.  -->
        <LexerType name="NWScript" desc="NWScript files" ext="">
            <!--
			The WordStyle tags describe how to colorize each type of language token. Here, all WordStyles which have a 
			<WordStyle keywordClass=""> attribute must match with a respective language <Keyword name="">. All other unassociated 
			tags are treated internally by the language lexer, such as Preprocessor Directives, Default colors, Numbers, Strings, 
			Operators and Comments.
			The name is what Notepad++ displays to the user in the Settings -> Style Configurator box.
			The styleID attribute is an internal number the lexer software uses to associate classes and should NEVER be changed.  -->
            <WordsStyle name="PREPROCESSOR" styleID="9" fgColor="804000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize=""/>
            <WordsStyle name="DEFAULT" styleID="11" fgColor="000000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize=""/>
            <WordsStyle name="INSTRUCTION WORD" styleID="5" fgColor="0000FF" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="instre1"/>
            <WordsStyle name="TYPE WORD" styleID="16" fgColor="AA00AA" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type1"/>
            <WordsStyle name="ENGINE TYPE" styleID="28" fgColor="FF09FF" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type2"/>
            <WordsStyle name="OBJECT TYPE" styleID="29" fgColor="0065CA" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize="" keywordClass="type3"/>
            <WordsStyle name="ENGINE CONSTANT" styleID="30" fgColor="0075EA" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type4"/>
            <WordsStyle name="CUSTOM CONSTANT" styleID="31" fgColor="0057AE" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type5"/>
            <WordsStyle name="ENGINE FUNCTION" styleID="32" fgColor="8000FF" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type6"/>
            <WordsStyle name="USER FUNCTION" styleID="36" fgColor="5200A4" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize="" keywordClass="type7"/>
            <WordsStyle name="NUMBER" styleID="4" fgColor="FF8000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize=""/>
            <WordsStyle name="STRING" styleID="6" fgColor="808080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize=""/>
            <WordsStyle name="OPERATOR" styleID="10" fgColor="000080" bgColor="FFFFFF" fontName="" fontStyle="1" fontSize=""/>
            <WordsStyle name="COMMENT" styleID="1" fgColor="008080" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize=""/>
            <WordsStyle name="COMMENT LINE" styleID="2" fgColor="008000" bgColor="FFFFFF" fontName="" fontStyle="0" fontSize=""/>
        </LexerType>
    </LexerStyles>
</NotepadPlus>
)"