name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, x86]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
         submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: vcpkg install
      run: vcpkg integrate install

    - name: MSBuild of plugin dll
      working-directory: .
      run: msbuild NWScript-Npp.sln /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v143"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: plugin_dll_x64
          path: bin\${{ matrix.build_platform }}\${{ matrix.build_configuration }}\NWScript-Npp.dll

    - name: Archive artifacts for Win32
      if: matrix.build_platform == 'x86' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: plugin_dll_x86
          path: bin\${{ matrix.build_platform }}\${{ matrix.build_configuration }}\NWScript-Npp.dll
